version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: on-failure
    container_name: postgres-pedidos
    build:
      context: ./db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  django:
    build:
      context: ./backend
    container_name: django-pedidos
    networks:
      default:
        aliases:
          - django
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env 
    environment: 
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
  
  wso2mi:
    build:
      context: .
      dockerfile: Dockerfile.wso2mi
    container_name: wso2mi-pedidos
    ports:
      - "8290:8290"
      - "8253:8253"
      - "9201:9201"
    restart: always
    environment:
      - JAVA_OPTS=-Xms256m -Xmx1024m
    depends_on:
      - django
      
volumes:
  postgres_data:

